# default: &default
#   # adapter: sqlite3
#   max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   # timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3

# test:
#   <<: *default
#   database: storage/test.sqlite3

# production:
#   primary:
#     <<: *default
#     adapter: postgresql
#     url: <%= ENV['DATABASE_URL'] %>
#   cache:
#     <<: *default
#     adapter: postgresql
#     url: <%= ENV['DATABASE_URL'] %>
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     adapter: postgresql
#     url: <%= ENV['DATABASE_URL'] %>
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     adapter: postgresql
#     url: <%= ENV['DATABASE_URL'] %>
#     migrations_paths: db/cable_migrate

# ===========================================================================
# SQLite (Local)
# ===========================================================================
sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *sqlite
  database: storage/development.sqlite3

test:
  <<: *sqlite
  database: storage/test.sqlite3

# ===========================================================================
# PostgreSQL (Heroku)
# ===========================================================================
postgres: &postgres
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  primary:
    <<: *postgres
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *postgres
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *postgres
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *postgres
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate


